//! Merkle proof and signature block cross-implementation tests for Go compatibility.
//!
//! These test vectors were generated from the Go DefraDB implementation
//! to ensure the Rust crypto implementation produces identical outputs.

use crypto::keys::ed25519::{Ed25519PrivateKey, Ed25519PublicKey};
use crypto::keys::secp256k1::{Secp256k1PrivateKey, Secp256k1PublicKey};
use crypto::keys::{Key, PrivateKey, PublicKey};
use defra_core::{Signature, SignatureHeader, SignatureType};

// Key constants needed for signature block tests
const ED25519_PRIVATE_KEY: [u8; 64] = [
    0x9d, 0x61, 0xb1, 0x9d, 0xef, 0xfd, 0x5a, 0x60, 0xba, 0x84, 0x4a, 0xf4, 0x92, 0xec, 0x2c,
    0xc4, 0x44, 0x49, 0xc5, 0x69, 0x7b, 0x32, 0x69, 0x19, 0x70, 0x3b, 0xac, 0x03, 0x1c, 0xae,
    0x7f, 0x60, 0xd7, 0x5a, 0x98, 0x01, 0x82, 0xb1, 0x0a, 0xb7, 0xd5, 0x4b, 0xfe, 0xd3, 0xc9,
    0x64, 0x07, 0x3a, 0x0e, 0xe1, 0x72, 0xf3, 0xda, 0xa6, 0x23, 0x25, 0xaf, 0x02, 0x1a, 0x68,
    0xf7, 0x07, 0x51, 0x1a,
];
const ED25519_PUBLIC_KEY: [u8; 32] = [
    0xd7, 0x5a, 0x98, 0x01, 0x82, 0xb1, 0x0a, 0xb7, 0xd5, 0x4b, 0xfe, 0xd3, 0xc9, 0x64, 0x07,
    0x3a, 0x0e, 0xe1, 0x72, 0xf3, 0xda, 0xa6, 0x23, 0x25, 0xaf, 0x02, 0x1a, 0x68, 0xf7, 0x07,
    0x51, 0x1a,
];
const SECP256K1_PRIVATE_KEY: [u8; 32] = [
    0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
    0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e,
    0x1f, 0x20,
];
const SECP256K1_PUBLIC_KEY_COMPRESSED: [u8; 33] = [
    0x02, 0x84, 0xbf, 0x75, 0x62, 0x26, 0x2b, 0xbd, 0x69, 0x40, 0x08, 0x57, 0x48, 0xf3, 0xbe,
    0x6a, 0xfa, 0x52, 0xae, 0x31, 0x71, 0x55, 0x18, 0x1e, 0xce, 0x31, 0xb6, 0x63, 0x51, 0xcc,
    0xff, 0xa4, 0xb0,
];

// ===== Merkle Proof / Signature Block Compatibility Tests =====
// These vectors were generated by Go DefraDB using:
//   go run ./tools/genvectors/

// Test block (DAG-CBOR encoded LWW delta)
const MERKLE_TEST_BLOCK_CBOR: &str = "a16564656c7461a1636c7777a564646174614a746573742d76616c756565646f6349444b746573742d646f632d6964687072696f7269747901696669656c644e616d65646e616d656f736368656d6156657273696f6e4944627631";

// Ed25519 signature block (DAG-CBOR) - signs the test block above
const ED25519_SIG_BLOCK_CBOR: &str = "a26576616c7565584045ef2233bc603ae79f2452a0c7ecf3ead41095c6ff1f6f8ca8e7329c12b471d0d4b201daa1ff96da0780c45b0915bd29fd622a1a8f71067449821886e5c8ab0666686561646572a26474797065654564445341686964656e74697479584064373561393830313832623130616237643534626665643363393634303733613065653137326633646161363233323561663032316136386637303735313161";

// secp256k1 signature block (DAG-CBOR) - signs the test block above
const SECP256K1_SIG_BLOCK_CBOR: &str = "a26576616c75655846304402201bee223f729683411a2a8873eada8f1ff95285da532891f6f296fba8b2388230022004cf45c5d7d10ef3721f4cb07a3ade8624d1fede02012973b9616cefa6cf887466686561646572a264747970656645533235364b686964656e746974795842303238346266373536323236326262643639343030383537343866336265366166613532616533313731353531383165636533316236363335316363666661346230";

#[test]
fn test_decode_go_signature_block_ed25519() {
    let sig_bytes = hex::decode(ED25519_SIG_BLOCK_CBOR).expect("Should decode hex");
    let signature: Signature =
        serde_ipld_dagcbor::from_slice(&sig_bytes).expect("Should decode DAG-CBOR signature");

    // Verify signature type
    assert_eq!(
        signature.header.sig_type,
        SignatureType::EdDSA,
        "Signature type should be EdDSA"
    );

    // Verify identity is hex-encoded public key string as bytes
    let identity_str =
        String::from_utf8(signature.header.identity.clone()).expect("Identity should be UTF-8");
    assert_eq!(
        identity_str, "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a",
        "Ed25519 identity should be hex-encoded public key"
    );

    // Verify the signature value is 64 bytes (Ed25519 signature)
    assert_eq!(
        signature.value.len(),
        64,
        "Ed25519 signature should be 64 bytes"
    );
}

#[test]
fn test_decode_go_signature_block_secp256k1() {
    let sig_bytes = hex::decode(SECP256K1_SIG_BLOCK_CBOR).expect("Should decode hex");
    let signature: Signature =
        serde_ipld_dagcbor::from_slice(&sig_bytes).expect("Should decode DAG-CBOR signature");

    // Verify signature type
    assert_eq!(
        signature.header.sig_type,
        SignatureType::ES256K,
        "Signature type should be ES256K"
    );

    // Verify identity is hex-encoded public key string as bytes
    let identity_str =
        String::from_utf8(signature.header.identity.clone()).expect("Identity should be UTF-8");
    assert_eq!(
        identity_str, "0284bf7562262bbd6940085748f3be6afa52ae317155181ece31b66351ccffa4b0",
        "secp256k1 identity should be hex-encoded compressed public key"
    );

    // secp256k1 DER signature should be variable length (typically 70-72 bytes)
    assert!(
        signature.value.len() >= 68 && signature.value.len() <= 72,
        "secp256k1 DER signature should be 68-72 bytes, got {}",
        signature.value.len()
    );
}

#[test]
fn test_verify_go_ed25519_signature_on_block() {
    // Decode the block bytes
    let block_bytes = hex::decode(MERKLE_TEST_BLOCK_CBOR).expect("Should decode block hex");

    // Decode the signature
    let sig_bytes = hex::decode(ED25519_SIG_BLOCK_CBOR).expect("Should decode sig hex");
    let signature: Signature =
        serde_ipld_dagcbor::from_slice(&sig_bytes).expect("Should decode signature");

    // Get the public key from the test vectors (same key used in other tests)
    let public_key =
        Ed25519PublicKey::from_bytes(&ED25519_PUBLIC_KEY).expect("Should parse public key");

    // Verify the signature
    let valid = public_key
        .verify(&block_bytes, &signature.value)
        .expect("Verification should not error");

    assert!(valid, "Go-generated Ed25519 signature should verify");
}

#[test]
fn test_verify_go_secp256k1_signature_on_block() {
    // Decode the block bytes
    let block_bytes = hex::decode(MERKLE_TEST_BLOCK_CBOR).expect("Should decode block hex");

    // Decode the signature
    let sig_bytes = hex::decode(SECP256K1_SIG_BLOCK_CBOR).expect("Should decode sig hex");
    let signature: Signature =
        serde_ipld_dagcbor::from_slice(&sig_bytes).expect("Should decode signature");

    // Get the public key from the test vectors (same key used in other tests)
    let public_key = Secp256k1PublicKey::from_bytes(&SECP256K1_PUBLIC_KEY_COMPRESSED)
        .expect("Should parse public key");

    // Verify the signature
    let valid = public_key
        .verify(&block_bytes, &signature.value)
        .expect("Verification should not error");

    assert!(valid, "Go-generated secp256k1 signature should verify");
}

#[test]
fn test_rust_signature_format_matches_go_ed25519() {
    // Sign the same block bytes with the same key
    let block_bytes = hex::decode(MERKLE_TEST_BLOCK_CBOR).expect("Should decode block hex");
    let private_key = Ed25519PrivateKey::from_bytes(&ED25519_PRIVATE_KEY).unwrap();

    // Create signature the same way Go does
    let signature_value = private_key.sign(&block_bytes).unwrap();

    // Identity should be hex-encoded public key string as bytes (Go format)
    let identity = private_key.public_key().to_hex_string().into_bytes();

    let rust_signature = Signature {
        header: SignatureHeader {
            sig_type: SignatureType::EdDSA,
            identity,
        },
        value: signature_value,
    };

    // Serialize to DAG-CBOR
    let rust_sig_bytes =
        serde_ipld_dagcbor::to_vec(&rust_signature).expect("Should serialize signature");

    // Decode Go signature for comparison
    let go_sig_bytes = hex::decode(ED25519_SIG_BLOCK_CBOR).expect("Should decode Go sig");

    // The serialized bytes should match exactly
    assert_eq!(
        rust_sig_bytes, go_sig_bytes,
        "Rust-generated Ed25519 signature block should match Go format exactly"
    );
}

#[test]
fn test_rust_signature_format_matches_go_secp256k1() {
    // Sign the same block bytes with the same key
    let block_bytes = hex::decode(MERKLE_TEST_BLOCK_CBOR).expect("Should decode block hex");
    let private_key = Secp256k1PrivateKey::from_bytes(&SECP256K1_PRIVATE_KEY).unwrap();

    // Create signature the same way Go does
    let signature_value = private_key.sign(&block_bytes).unwrap();

    // Identity should be hex-encoded public key string as bytes (Go format)
    let identity = private_key.public_key().to_hex_string().into_bytes();

    let rust_signature = Signature {
        header: SignatureHeader {
            sig_type: SignatureType::ES256K,
            identity,
        },
        value: signature_value,
    };

    // Serialize to DAG-CBOR
    let rust_sig_bytes =
        serde_ipld_dagcbor::to_vec(&rust_signature).expect("Should serialize signature");

    // Decode Go signature for comparison
    let go_sig_bytes = hex::decode(SECP256K1_SIG_BLOCK_CBOR).expect("Should decode Go sig");

    // The serialized bytes should match exactly
    assert_eq!(
        rust_sig_bytes, go_sig_bytes,
        "Rust-generated secp256k1 signature block should match Go format exactly"
    );
}

#[test]
fn test_identity_format_roundtrip() {
    // Verify that we can parse the identity from Go signature and reconstruct the public key

    // Ed25519
    let ed25519_identity_hex =
        "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a";
    let ed25519_key_bytes = hex::decode(ed25519_identity_hex).expect("Should decode hex");
    let ed25519_pubkey =
        Ed25519PublicKey::from_bytes(&ed25519_key_bytes).expect("Should parse Ed25519 key");
    assert_eq!(
        ed25519_pubkey.to_hex_string(),
        ed25519_identity_hex,
        "Ed25519 identity should roundtrip"
    );

    // secp256k1
    let secp256k1_identity_hex =
        "0284bf7562262bbd6940085748f3be6afa52ae317155181ece31b66351ccffa4b0";
    let secp256k1_key_bytes = hex::decode(secp256k1_identity_hex).expect("Should decode hex");
    let secp256k1_pubkey = Secp256k1PublicKey::from_bytes(&secp256k1_key_bytes)
        .expect("Should parse secp256k1 key");
    assert_eq!(
        secp256k1_pubkey.to_hex_string(),
        secp256k1_identity_hex,
        "secp256k1 identity should roundtrip"
    );
}
