//! CID (Content Identifier) generation for schema definitions.
//!
//! This module generates CIDs compatible with Go DefraDB's IPLD block format.
//! Uses defra-core's Block type with serde_ipld_dagcbor for proper DAG-CBOR encoding.

use cid::Cid;
use defra_core::{
    Block, CollectionDefinitionDeltaPayload, CrdtDelta, FieldDefinitionDeltaPayload,
    DAG_CBOR_CODEC, SHA2_256_CODE,
};
use multihash::Multihash;
use sha2::{Digest, Sha256};

use crate::{FieldDescription, FieldKind};

/// Generates a CID for a field definition.
///
/// This matches Go's field definition block structure using defra-core's Block type.
pub fn generate_field_cid(field: &FieldDescription) -> crate::Result<Cid> {
    let delta = field_to_delta(field)?;
    let block = Block::new(CrdtDelta::FieldDefinition(delta), vec![], vec![]);
    generate_block_cid(&block)
}

/// Generates a CID for a collection definition.
///
/// This matches Go's collection definition block structure using defra-core's Block type.
pub fn generate_collection_cid(name: &str, _field_cids: &[Cid]) -> crate::Result<Cid> {
    let delta = CollectionDefinitionDeltaPayload::new(1).with_name(name);
    let block = Block::new(CrdtDelta::CollectionDefinition(delta), vec![], vec![]);
    generate_block_cid(&block)
}

/// Generates a CID from a Block using DAG-CBOR encoding.
fn generate_block_cid(block: &Block) -> crate::Result<Cid> {
    // Serialize to DAG-CBOR using serde_ipld_dagcbor
    let cbor_bytes = block
        .to_dag_cbor()
        .map_err(|e| crate::SchemaError::CidGeneration(e.to_string()))?;

    // Hash with SHA2-256
    let mut hasher = Sha256::new();
    hasher.update(&cbor_bytes);
    let hash_bytes = hasher.finalize();

    // Create multihash (CID crate uses Multihash<64>)
    let mh: Multihash<64> = Multihash::wrap(SHA2_256_CODE, &hash_bytes)
        .map_err(|e| crate::SchemaError::CidGeneration(e.to_string()))?;

    // Create CIDv1 with DAG-CBOR codec
    let cid = Cid::new_v1(DAG_CBOR_CODEC, mh);
    Ok(cid)
}

/// Convert a FieldDescription to a FieldDefinitionDeltaPayload
fn field_to_delta(field: &FieldDescription) -> crate::Result<FieldDefinitionDeltaPayload> {
    let mut delta = FieldDefinitionDeltaPayload::new(1)
        .with_name(&field.name)
        .with_crdt(field.crdt_type as u8);

    match &field.kind {
        FieldKind::Scalar(k) => {
            delta = delta.with_scalar_kind(*k as u8);
        }
        FieldKind::ScalarArray(k) => {
            delta = delta.with_scalar_kind(*k as u8);
        }
        FieldKind::Relation { collection_id, .. } => {
            delta = delta.with_collection_id(collection_id);
        }
        FieldKind::SelfRef { relative_id, .. } => {
            if !relative_id.is_empty() {
                let rel_id = relative_id.parse::<i32>().map_err(|e| {
                    crate::SchemaError::CidGeneration(format!(
                        "Invalid relative_id '{}': {}",
                        relative_id, e
                    ))
                })?;
                delta = delta.with_relative_id(rel_id);
            }
        }
        FieldKind::Named { .. } => {}
    }

    Ok(delta)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::CType;

    // Go-generated CID fixtures for verification
    // Generated by: go test -v -run TestGenerateCIDFixtures ./client/
    const GO_CID_FIELD_DOCID: &str = "bafyreibmf7lqchqcal3j6zupiwo5fkn2ax7n25wszdygsibv7ybgdi6cny";
    const GO_CID_FIELD_STRING: &str = "bafyreiaezc5g33yzhyzcgbyiv476lovyztyoliotzksdfogoep5ktgpedq";
    const GO_CID_FIELD_INT: &str = "bafyreiefugdbpc563kqcjoe4pjrgavtv3ysbhpzp5smdwb4stxeldmronm";
    const GO_CID_FIELD_RELATION: &str =
        "bafyreibzyoyhnkjp3byipqvvpplbgxq5c5aeiy5zdu773gb7zbxdmsvlym";
    const GO_CID_COLLECTION_USERS: &str =
        "bafyreiazcyzp3lzapqxuf3b6pw6himmcun65ljkaxmgsbxngdfrcbcfg7e";

    #[test]
    fn test_field_docid_cid_matches_go() {
        let field = FieldDescription::new("1", "_docID", FieldKind::doc_id());
        let cid = generate_field_cid(&field).unwrap();
        assert_eq!(
            cid.to_string(),
            GO_CID_FIELD_DOCID,
            "Rust CID for _docID field should match Go"
        );
    }

    #[test]
    fn test_field_string_cid_matches_go() {
        let field = FieldDescription::new("1", "name", FieldKind::string());
        let cid = generate_field_cid(&field).unwrap();
        assert_eq!(
            cid.to_string(),
            GO_CID_FIELD_STRING,
            "Rust CID for string field should match Go"
        );
    }

    #[test]
    fn test_field_int_cid_matches_go() {
        let field = FieldDescription::new("1", "age", FieldKind::int());
        let cid = generate_field_cid(&field).unwrap();
        assert_eq!(
            cid.to_string(),
            GO_CID_FIELD_INT,
            "Rust CID for int field should match Go"
        );
    }

    #[test]
    fn test_field_relation_cid_matches_go() {
        let field =
            FieldDescription::new("1", "author", FieldKind::relation("bafkreiusers123", false))
                .with_crdt_type(CType::Object);
        let cid = generate_field_cid(&field).unwrap();
        assert_eq!(
            cid.to_string(),
            GO_CID_FIELD_RELATION,
            "Rust CID for relation field should match Go"
        );
    }

    #[test]
    fn test_collection_cid_matches_go() {
        let cid = generate_collection_cid("users", &[]).unwrap();
        assert_eq!(
            cid.to_string(),
            GO_CID_COLLECTION_USERS,
            "Rust CID for collection should match Go"
        );
    }

    #[test]
    fn test_field_cid_generation() {
        let field = FieldDescription::new("1", "_docID", FieldKind::doc_id());
        let cid = generate_field_cid(&field).unwrap();

        // CID should be a valid CIDv1
        assert_eq!(cid.version(), cid::Version::V1);
        assert_eq!(cid.codec(), DAG_CBOR_CODEC);

        // Same field should produce same CID (deterministic)
        let cid2 = generate_field_cid(&field).unwrap();
        assert_eq!(cid, cid2);
    }

    #[test]
    fn test_collection_cid_generation() {
        let field1 = FieldDescription::new("1", "_docID", FieldKind::doc_id());
        let field2 = FieldDescription::new("2", "name", FieldKind::string());

        let cid1 = generate_field_cid(&field1).unwrap();
        let cid2 = generate_field_cid(&field2).unwrap();

        let collection_cid = generate_collection_cid("users", &[cid1, cid2]).unwrap();

        assert_eq!(collection_cid.version(), cid::Version::V1);
        assert_eq!(collection_cid.codec(), DAG_CBOR_CODEC);
    }

    #[test]
    fn test_different_fields_produce_different_cids() {
        let field1 = FieldDescription::new("1", "name", FieldKind::string());
        let field2 = FieldDescription::new("2", "age", FieldKind::int());

        let cid1 = generate_field_cid(&field1).unwrap();
        let cid2 = generate_field_cid(&field2).unwrap();

        assert_ne!(cid1, cid2);
    }

    #[test]
    fn test_self_ref_field_cid() {
        let kind = FieldKind::SelfRef {
            relative_id: "0".to_string(),
            is_array: false,
        };
        let field = FieldDescription::new("1", "parent", kind).with_crdt_type(CType::Object);

        let cid = generate_field_cid(&field).unwrap();
        assert_eq!(cid.version(), cid::Version::V1);
    }

    #[test]
    fn test_cid_string_format() {
        let field = FieldDescription::new("1", "_docID", FieldKind::doc_id());
        let cid = generate_field_cid(&field).unwrap();

        let cid_str = cid.to_string();
        // CIDv1 base32 strings start with 'bafy'
        assert!(
            cid_str.starts_with("bafy"),
            "CID should be base32 encoded: {}",
            cid_str
        );
    }
}
