[package]
name = "crdt"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.cargo-machete]
ignored = ["serde_json", "thiserror"]

[dependencies]
defra-core = { path = "../defra-core" }
storage = { path = "../storage" }

# Async
async-trait.workspace = true

# Serialization
serde.workspace = true
serde_json.workspace = true

# Error handling
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
criterion.workspace = true
proptest.workspace = true
tokio = { workspace = true, features = ["test-util"] }

[[bench]]
name = "merge"
harness = false

[lints]
workspace = true
