[package]
name = "schema"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
defra-core = { path = "../defra-core" }
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_cbor.workspace = true
cid.workspace = true
multihash.workspace = true
sha2.workspace = true

[dev-dependencies]
proptest.workspace = true
