[package]
name = "datastore"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Transaction wrapper for DefraDB providing multistore access and callbacks"

[dependencies]
# Async runtime
async-trait.workspace = true
async-lock.workspace = true
futures.workspace = true

# Error handling
thiserror.workspace = true

# Logging
tracing.workspace = true

# IPLD
cid.workspace = true

# Internal crates
storage = { path = "../storage" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["rt"] }

[dev-dependencies]
# Testing
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
