//! Tests for CID (Content Identifier) generation.
//!
//! These tests verify:
//! - CID generation matches Go DefraDB format
//! - Deterministic CID generation
//! - CIDv1 with DAG-CBOR codec
//! - Go compatibility fixtures

use schema::{generate_collection_cid, generate_field_cid, CType, FieldDescription, FieldKind};

// Go-generated CID fixtures for verification
// Generated by: go test -v -run TestGenerateCIDFixtures ./client/
const GO_CID_FIELD_DOCID: &str = "bafyreibmf7lqchqcal3j6zupiwo5fkn2ax7n25wszdygsibv7ybgdi6cny";
const GO_CID_FIELD_STRING: &str = "bafyreiaezc5g33yzhyzcgbyiv476lovyztyoliotzksdfogoep5ktgpedq";
const GO_CID_FIELD_INT: &str = "bafyreiefugdbpc563kqcjoe4pjrgavtv3ysbhpzp5smdwb4stxeldmronm";
const GO_CID_FIELD_RELATION: &str = "bafyreibzyoyhnkjp3byipqvvpplbgxq5c5aeiy5zdu773gb7zbxdmsvlym";
const GO_CID_COLLECTION_USERS: &str = "bafyreiazcyzp3lzapqxuf3b6pw6himmcun65ljkaxmgsbxngdfrcbcfg7e";

// ============================================================================
// Go Compatibility Tests
// ============================================================================

#[test]
fn test_field_docid_cid_matches_go() {
    let field = FieldDescription::new("1", "_docID", FieldKind::doc_id());
    let cid = generate_field_cid(&field).unwrap();
    assert_eq!(
        cid.to_string(),
        GO_CID_FIELD_DOCID,
        "Rust CID for _docID field should match Go"
    );
}

#[test]
fn test_field_string_cid_matches_go() {
    let field = FieldDescription::new("1", "name", FieldKind::string());
    let cid = generate_field_cid(&field).unwrap();
    assert_eq!(
        cid.to_string(),
        GO_CID_FIELD_STRING,
        "Rust CID for string field should match Go"
    );
}

#[test]
fn test_field_int_cid_matches_go() {
    let field = FieldDescription::new("1", "age", FieldKind::int());
    let cid = generate_field_cid(&field).unwrap();
    assert_eq!(
        cid.to_string(),
        GO_CID_FIELD_INT,
        "Rust CID for int field should match Go"
    );
}

#[test]
fn test_field_relation_cid_matches_go() {
    let field = FieldDescription::new("1", "author", FieldKind::relation("bafkreiusers123", false))
        .with_crdt_type(CType::Object);
    let cid = generate_field_cid(&field).unwrap();
    assert_eq!(
        cid.to_string(),
        GO_CID_FIELD_RELATION,
        "Rust CID for relation field should match Go"
    );
}

#[test]
fn test_collection_cid_matches_go() {
    let cid = generate_collection_cid("users", &[]).unwrap();
    assert_eq!(
        cid.to_string(),
        GO_CID_COLLECTION_USERS,
        "Rust CID for collection should match Go"
    );
}

// ============================================================================
// CID Format Tests
// ============================================================================

#[test]
fn test_field_cid_generation() {
    let field = FieldDescription::new("1", "_docID", FieldKind::doc_id());
    let cid = generate_field_cid(&field).unwrap();

    // CID should be a valid CIDv1
    assert_eq!(cid.version(), cid::Version::V1);
    assert_eq!(cid.codec(), 0x71); // DAG-CBOR codec

    // Same field should produce same CID (deterministic)
    let cid2 = generate_field_cid(&field).unwrap();
    assert_eq!(cid, cid2);
}

#[test]
fn test_collection_cid_generation() {
    let field1 = FieldDescription::new("1", "_docID", FieldKind::doc_id());
    let field2 = FieldDescription::new("2", "name", FieldKind::string());

    let cid1 = generate_field_cid(&field1).unwrap();
    let cid2 = generate_field_cid(&field2).unwrap();

    let collection_cid = generate_collection_cid("users", &[cid1, cid2]).unwrap();

    assert_eq!(collection_cid.version(), cid::Version::V1);
    assert_eq!(collection_cid.codec(), 0x71); // DAG-CBOR codec
}

#[test]
fn test_different_fields_produce_different_cids() {
    let field1 = FieldDescription::new("1", "name", FieldKind::string());
    let field2 = FieldDescription::new("2", "age", FieldKind::int());

    let cid1 = generate_field_cid(&field1).unwrap();
    let cid2 = generate_field_cid(&field2).unwrap();

    assert_ne!(cid1, cid2);
}

#[test]
fn test_self_ref_field_cid() {
    let kind = FieldKind::SelfRef {
        relative_id: "0".to_string(),
        is_array: false,
    };
    let field = FieldDescription::new("1", "parent", kind).with_crdt_type(CType::Object);

    let cid = generate_field_cid(&field).unwrap();
    assert_eq!(cid.version(), cid::Version::V1);
}

#[test]
fn test_cid_string_format() {
    let field = FieldDescription::new("1", "_docID", FieldKind::doc_id());
    let cid = generate_field_cid(&field).unwrap();

    let cid_str = cid.to_string();
    // CIDv1 base32 strings start with 'bafy'
    assert!(
        cid_str.starts_with("bafy"),
        "CID should be base32 encoded: {}",
        cid_str
    );
}

// ============================================================================
// Debug Test - Print CIDs for Users schema
// ============================================================================

#[test]
fn debug_users_schema_cids() {
    use schema::generate_field_cid_with_priority;

    println!("\n=== Debug: Users schema CID generation ===");

    // Field 1: _docID (priority 1)
    let doc_id = FieldDescription::new("1", "_docID", FieldKind::doc_id());
    let doc_id_cid = generate_field_cid_with_priority(&doc_id, 1).unwrap();
    println!("_docID (p=1): {} crdt={}", doc_id_cid, doc_id.crdt_type as u8);

    // Field 2: name (priority 2)
    let name = FieldDescription::new("2", "name", FieldKind::string());
    let name_cid = generate_field_cid_with_priority(&name, 2).unwrap();
    println!("name (p=2): {} crdt={}", name_cid, name.crdt_type as u8);

    // Field 3: age (priority 3)
    let age = FieldDescription::new("3", "age", FieldKind::int());
    let age_cid = generate_field_cid_with_priority(&age, 3).unwrap();
    println!("age (p=3): {} crdt={}", age_cid, age.crdt_type as u8);

    // Collection with field links
    let field_cids = vec![doc_id_cid, name_cid, age_cid];
    let collection_cid = generate_collection_cid("Users", &field_cids).unwrap();
    println!("Collection 'Users': {}", collection_cid);

    // Also test without field CIDs
    let collection_cid_no_fields = generate_collection_cid("Users", &[]).unwrap();
    println!("Collection 'Users' (no fields): {}", collection_cid_no_fields);

    println!();
}
#[test]
fn debug_detailed_field_encoding() {
    use schema::{generate_field_cid_with_priority, CType, FieldDescription, FieldKind};

    println!("\n=== Detailed Field Debug ===");
    
    // _docID with CType::None (like Go)
    let doc_id = FieldDescription::new("1", "_docID", FieldKind::doc_id())
        .with_crdt_type(CType::None);
    let doc_id_cid = generate_field_cid_with_priority(&doc_id, 1).unwrap();
    println!("_docID: crdt={}, scalarKind={:?}, cid={}", 
             doc_id.crdt_type as u8, 
             match &doc_id.kind { 
                 schema::FieldKind::Scalar(k) => *k as u8,
                 _ => 255
             },
             doc_id_cid);

    // age with CType::LwwRegister (default)
    let age = FieldDescription::new("2", "age", FieldKind::int());
    let age_cid = generate_field_cid_with_priority(&age, 2).unwrap();
    println!("age: crdt={}, scalarKind={:?}, cid={}", 
             age.crdt_type as u8, 
             match &age.kind { 
                 schema::FieldKind::Scalar(k) => *k as u8,
                 _ => 255
             },
             age_cid);

    // name with CType::LwwRegister (default)
    let name = FieldDescription::new("3", "name", FieldKind::string());
    let name_cid = generate_field_cid_with_priority(&name, 3).unwrap();
    println!("name: crdt={}, scalarKind={:?}, cid={}", 
             name.crdt_type as u8, 
             match &name.kind { 
                 schema::FieldKind::Scalar(k) => *k as u8,
                 _ => 255
             },
             name_cid);

    // Collection with sorted fields
    let collection_cid = schema::generate_collection_cid("Users", &[doc_id_cid, age_cid, name_cid]).unwrap();
    println!("\nCollection 'Users': {}", collection_cid);
    
    // Compare with Go expected
    println!("\nGo expected: bafyreihsneodeja4lfer5puptim3lkwvketyckrmkhfpgxm67ch5wenjwq");
}
