//! Tests for CID (Content Identifier) generation.
//!
//! These tests verify:
//! - CID generation matches Go DefraDB format
//! - Deterministic CID generation
//! - CIDv1 with DAG-CBOR codec
//! - Go compatibility fixtures

use schema::{generate_collection_cid, generate_field_cid, CType, FieldDescription, FieldKind};

// Go-generated CID fixtures for verification
// Generated by: go test -v -run TestGenerateCIDFixtures ./client/
const GO_CID_FIELD_DOCID: &str = "bafyreibmf7lqchqcal3j6zupiwo5fkn2ax7n25wszdygsibv7ybgdi6cny";
const GO_CID_FIELD_STRING: &str = "bafyreiaezc5g33yzhyzcgbyiv476lovyztyoliotzksdfogoep5ktgpedq";
const GO_CID_FIELD_INT: &str = "bafyreiefugdbpc563kqcjoe4pjrgavtv3ysbhpzp5smdwb4stxeldmronm";
const GO_CID_FIELD_RELATION: &str =
    "bafyreibzyoyhnkjp3byipqvvpplbgxq5c5aeiy5zdu773gb7zbxdmsvlym";
const GO_CID_COLLECTION_USERS: &str =
    "bafyreiazcyzp3lzapqxuf3b6pw6himmcun65ljkaxmgsbxngdfrcbcfg7e";

// ============================================================================
// Go Compatibility Tests
// ============================================================================

#[test]
fn test_field_docid_cid_matches_go() {
    let field = FieldDescription::new("1", "_docID", FieldKind::doc_id());
    let cid = generate_field_cid(&field).unwrap();
    assert_eq!(
        cid.to_string(),
        GO_CID_FIELD_DOCID,
        "Rust CID for _docID field should match Go"
    );
}

#[test]
fn test_field_string_cid_matches_go() {
    let field = FieldDescription::new("1", "name", FieldKind::string());
    let cid = generate_field_cid(&field).unwrap();
    assert_eq!(
        cid.to_string(),
        GO_CID_FIELD_STRING,
        "Rust CID for string field should match Go"
    );
}

#[test]
fn test_field_int_cid_matches_go() {
    let field = FieldDescription::new("1", "age", FieldKind::int());
    let cid = generate_field_cid(&field).unwrap();
    assert_eq!(
        cid.to_string(),
        GO_CID_FIELD_INT,
        "Rust CID for int field should match Go"
    );
}

#[test]
fn test_field_relation_cid_matches_go() {
    let field =
        FieldDescription::new("1", "author", FieldKind::relation("bafkreiusers123", false))
            .with_crdt_type(CType::Object);
    let cid = generate_field_cid(&field).unwrap();
    assert_eq!(
        cid.to_string(),
        GO_CID_FIELD_RELATION,
        "Rust CID for relation field should match Go"
    );
}

#[test]
fn test_collection_cid_matches_go() {
    let cid = generate_collection_cid("users", &[]).unwrap();
    assert_eq!(
        cid.to_string(),
        GO_CID_COLLECTION_USERS,
        "Rust CID for collection should match Go"
    );
}

// ============================================================================
// CID Format Tests
// ============================================================================

#[test]
fn test_field_cid_generation() {
    let field = FieldDescription::new("1", "_docID", FieldKind::doc_id());
    let cid = generate_field_cid(&field).unwrap();

    // CID should be a valid CIDv1
    assert_eq!(cid.version(), cid::Version::V1);
    assert_eq!(cid.codec(), 0x71); // DAG-CBOR codec

    // Same field should produce same CID (deterministic)
    let cid2 = generate_field_cid(&field).unwrap();
    assert_eq!(cid, cid2);
}

#[test]
fn test_collection_cid_generation() {
    let field1 = FieldDescription::new("1", "_docID", FieldKind::doc_id());
    let field2 = FieldDescription::new("2", "name", FieldKind::string());

    let cid1 = generate_field_cid(&field1).unwrap();
    let cid2 = generate_field_cid(&field2).unwrap();

    let collection_cid = generate_collection_cid("users", &[cid1, cid2]).unwrap();

    assert_eq!(collection_cid.version(), cid::Version::V1);
    assert_eq!(collection_cid.codec(), 0x71); // DAG-CBOR codec
}

#[test]
fn test_different_fields_produce_different_cids() {
    let field1 = FieldDescription::new("1", "name", FieldKind::string());
    let field2 = FieldDescription::new("2", "age", FieldKind::int());

    let cid1 = generate_field_cid(&field1).unwrap();
    let cid2 = generate_field_cid(&field2).unwrap();

    assert_ne!(cid1, cid2);
}

#[test]
fn test_self_ref_field_cid() {
    let kind = FieldKind::SelfRef {
        relative_id: "0".to_string(),
        is_array: false,
    };
    let field = FieldDescription::new("1", "parent", kind).with_crdt_type(CType::Object);

    let cid = generate_field_cid(&field).unwrap();
    assert_eq!(cid.version(), cid::Version::V1);
}

#[test]
fn test_cid_string_format() {
    let field = FieldDescription::new("1", "_docID", FieldKind::doc_id());
    let cid = generate_field_cid(&field).unwrap();

    let cid_str = cid.to_string();
    // CIDv1 base32 strings start with 'bafy'
    assert!(
        cid_str.starts_with("bafy"),
        "CID should be base32 encoded: {}",
        cid_str
    );
}
