//! Node state management for FFI.
//!
//! This module manages the lifecycle of node instances and their handles.
//! Go code receives opaque usize handles that map to actual node state.

use std::collections::HashMap;
use std::collections::HashSet;
use std::sync::atomic::{AtomicU64, AtomicUsize, Ordering};
use std::sync::Arc;
use std::sync::OnceLock;

use parking_lot::RwLock;
use sha2::{Digest, Sha256};
use storage::MemoryStore;

use p2p::P2PHostHandle;

use crate::policy_yaml::ParsedPolicy;

/// In-memory policy store for DAC policies.
///
/// Generates Go-compatible policy IDs using parsed-field hashing
/// combined with a monotonic sequence counter.
pub struct PolicyStore {
    policies: RwLock<HashMap<String, String>>,
    counter: AtomicU64,
}

impl Default for PolicyStore {
    fn default() -> Self {
        Self::new()
    }
}

impl PolicyStore {
    /// Create a new empty policy store.
    pub fn new() -> Self {
        Self {
            policies: RwLock::new(HashMap::new()),
            counter: AtomicU64::new(1), // Go's counter starts at 1 (GetNext returns currID + 1)
        }
    }

    /// Add a policy and return its Go-compatible ID.
    ///
    /// The ID is generated by:
    /// 1. Parsing the YAML into a sorted policy structure
    /// 2. Hashing the parsed fields (name, resources, relations, permissions)
    /// 3. Combining with a monotonic counter
    /// 4. SHA256(field_hash || counter_string)
    pub fn add_policy(&self, policy: &str, parsed: &ParsedPolicy) -> String {
        let counter_val = self.counter.fetch_add(1, Ordering::SeqCst);
        let policy_id = generate_policy_id(parsed, counter_val);

        self.policies
            .write()
            .insert(policy_id.clone(), policy.to_string());

        policy_id
    }

    /// Get a policy by ID.
    pub fn get_policy(&self, id: &str) -> Option<String> {
        self.policies.read().get(id).cloned()
    }

    /// List all policy IDs.
    pub fn list_policies(&self) -> Vec<String> {
        self.policies.read().keys().cloned().collect()
    }
}

/// Generate a Go-compatible policy ID from parsed policy fields.
///
/// Matches Go's `acp_core` `IdTransformer.Transform` + `hashPol`:
/// 1. Inner hash: SHA256(name + sorted_resources(name + sorted_relations(name) + sorted_permissions(name + expr)))
/// 2. Outer hash: SHA256(inner_hash_bytes + counter_as_string)
fn generate_policy_id(policy: &ParsedPolicy, counter: u64) -> String {
    let inner_hash = hash_policy_fields(policy);

    let mut outer_hasher = Sha256::new();
    outer_hasher.update(&inner_hash);
    outer_hasher.update(format!("{}", counter).as_bytes());

    let hash = outer_hasher.finalize();
    hex::encode(hash)
}

/// Hash the deterministic parsed fields of a policy.
///
/// Matches Go's `hashPol` function: sorts resources, relations, and permissions
/// by name before hashing.
fn hash_policy_fields(policy: &ParsedPolicy) -> Vec<u8> {
    let mut hasher = Sha256::new();
    hasher.update(policy.name.as_bytes());

    // Sort resources by name (Go's SortTransformer sorts before hashing)
    let mut resources: Vec<_> = policy.resources.iter().collect();
    resources.sort_by(|a, b| a.name.cmp(&b.name));

    for resource in resources {
        hasher.update(resource.name.as_bytes());

        // Sort relations by name
        let mut relations: Vec<_> = resource.relations.iter().collect();
        relations.sort_by(|a, b| a.name.cmp(&b.name));
        for relation in relations {
            hasher.update(relation.name.as_bytes());
        }

        // Sort permissions by name
        let mut permissions: Vec<_> = resource.permissions.iter().collect();
        permissions.sort_by(|a, b| a.name.cmp(&b.name));
        for permission in permissions {
            hasher.update(permission.name.as_bytes());
            hasher.update(permission.expr.as_bytes());
        }
    }

    hasher.finalize().to_vec()
}

/// P2P state for FFI nodes.
///
/// This wraps the P2P host handle and tracks P2P-specific state like
/// subscribed collections and background task handles.
pub struct P2PState {
    /// Handle to communicate with the P2P host.
    pub handle: P2PHostHandle,
    /// Collections subscribed for P2P replication (insertion-ordered).
    pub collections: RwLock<Vec<String>>,
    /// Documents subscribed for P2P replication (by doc ID).
    pub documents: RwLock<HashSet<String>>,
    /// Known peer addresses: peer_id_string -> full multiaddr with /p2p/ component.
    /// Populated when peers connect via p2p_connect or p2p_set_replicator.
    pub peer_addresses: RwLock<HashMap<String, String>>,
    /// Abort handle for the host event loop task.
    pub host_event_handle: Option<tokio::task::AbortHandle>,
    /// Abort handle for the replication loop task.
    pub replication_handle: Option<tokio::task::AbortHandle>,
    /// Abort handle for the local update broadcast task.
    pub broadcast_handle: Option<tokio::task::AbortHandle>,
}

impl P2PState {
    /// Create new P2P state with the given host handle.
    pub fn new(handle: P2PHostHandle) -> Self {
        Self {
            handle,
            collections: RwLock::new(Vec::new()),
            documents: RwLock::new(HashSet::new()),
            peer_addresses: RwLock::new(HashMap::new()),
            host_event_handle: None,
            replication_handle: None,
            broadcast_handle: None,
        }
    }

    /// Create new P2P state with sync pipeline abort handles.
    pub fn with_sync_pipeline(
        handle: P2PHostHandle,
        host_event_handle: tokio::task::AbortHandle,
        replication_handle: tokio::task::AbortHandle,
        broadcast_handle: tokio::task::AbortHandle,
    ) -> Self {
        Self {
            handle,
            collections: RwLock::new(Vec::new()),
            documents: RwLock::new(HashSet::new()),
            peer_addresses: RwLock::new(HashMap::new()),
            host_event_handle: Some(host_event_handle),
            replication_handle: Some(replication_handle),
            broadcast_handle: Some(broadcast_handle),
        }
    }

    /// Abort all background tasks.
    pub fn abort_all_tasks(&self) {
        if let Some(ref h) = self.host_event_handle {
            h.abort();
        }
        if let Some(ref h) = self.replication_handle {
            h.abort();
        }
        if let Some(ref h) = self.broadcast_handle {
            h.abort();
        }
    }

    /// Add a collection to P2P (preserves insertion order).
    pub fn add_collection(&self, name: &str) {
        let mut cols = self.collections.write();
        if !cols.contains(&name.to_string()) {
            cols.push(name.to_string());
        }
    }

    /// Remove a collection from P2P.
    pub fn remove_collection(&self, name: &str) -> bool {
        let mut cols = self.collections.write();
        if let Some(pos) = cols.iter().position(|c| c == name) {
            cols.remove(pos);
            true
        } else {
            false
        }
    }

    /// Get all P2P collections (in insertion order).
    pub fn get_collections(&self) -> Vec<String> {
        self.collections.read().clone()
    }

    /// Add a document to P2P.
    pub fn add_document(&self, doc_id: &str) {
        self.documents.write().insert(doc_id.to_string());
    }

    /// Remove a document from P2P.
    pub fn remove_document(&self, doc_id: &str) -> bool {
        self.documents.write().remove(doc_id)
    }

    /// Get all P2P documents.
    pub fn get_documents(&self) -> Vec<String> {
        self.documents.read().iter().cloned().collect()
    }

    /// Store a peer's full multiaddr (called on connect/set_replicator).
    pub fn set_peer_address(&self, peer_id: &str, full_multiaddr: &str) {
        self.peer_addresses
            .write()
            .insert(peer_id.to_string(), full_multiaddr.to_string());
    }

    /// Get the stored multiaddr for a peer.
    pub fn get_peer_address(&self, peer_id: &str) -> Option<String> {
        self.peer_addresses.read().get(peer_id).cloned()
    }
}

/// Type alias for the database type used in FFI.
pub type FfiDatabase = db::DB<MemoryStore>;

/// Type alias for node handles (opaque to FFI callers).
pub type NodeHandle = usize;

/// Type alias for the NAC manager used in FFI (in-memory).
pub type FfiNacManager = db::NacManager<acp::MemoryZanzibarStore>;

/// Type alias for subscription handles (opaque to FFI callers).
pub type SubscriptionHandle = usize;

/// State held for each FFI node.
pub struct NodeState {
    /// The database instance.
    pub database: Arc<FfiDatabase>,
    /// The query runner for executing GraphQL queries.
    pub query_runner: Arc<dyn query::QueryExecutor>,
    /// The NAC manager for node-level access control.
    pub nac_manager: Arc<FfiNacManager>,
    /// The document ACP for document-level access control.
    pub document_acp: Arc<dyn acp::DocumentACP>,
    /// The event bus for subscriptions.
    pub event_bus: Arc<dyn events::Bus>,
    /// The policy store for DAC policies.
    pub policy_store: Arc<PolicyStore>,
    /// P2P state (optional - not all nodes have P2P enabled).
    pub p2p: Option<Arc<P2PState>>,
}

/// State held for each FFI subscription.
pub struct SubscriptionState {
    /// The underlying events subscription.
    pub subscription: events::Subscription,
    /// The node handle this subscription belongs to.
    pub node_handle: NodeHandle,
    /// Optional collection name filter (None = all collections).
    pub collection_filter: Option<String>,
}

/// Global registry of active nodes.
///
/// Uses RwLock for safe concurrent access from multiple threads.
pub struct NodeRegistry {
    nodes: RwLock<HashMap<NodeHandle, NodeState>>,
    next_handle: AtomicUsize,
}

impl NodeRegistry {
    /// Create a new empty registry.
    fn new() -> Self {
        Self {
            nodes: RwLock::new(HashMap::new()),
            next_handle: AtomicUsize::new(1), // Start at 1, 0 is invalid
        }
    }

    /// Insert a new node state and return its handle.
    pub fn insert(&self, state: NodeState) -> NodeHandle {
        let handle = self.next_handle.fetch_add(1, Ordering::SeqCst);
        let mut nodes = self.nodes.write();
        nodes.insert(handle, state);
        handle
    }

    /// Get a reference to a node state.
    ///
    /// Returns None if the handle is invalid.
    pub fn get<F, R>(&self, handle: NodeHandle, f: F) -> Option<R>
    where
        F: FnOnce(&NodeState) -> R,
    {
        let nodes = self.nodes.read();
        nodes.get(&handle).map(f)
    }

    /// Remove and return a node state.
    ///
    /// Returns None if the handle is invalid.
    pub fn remove(&self, handle: NodeHandle) -> Option<NodeState> {
        let mut nodes = self.nodes.write();
        nodes.remove(&handle)
    }

    /// Check if a handle is valid.
    pub fn contains(&self, handle: NodeHandle) -> bool {
        let nodes = self.nodes.read();
        nodes.contains_key(&handle)
    }

    /// Get the number of active nodes.
    pub fn len(&self) -> usize {
        let nodes = self.nodes.read();
        nodes.len()
    }

    /// Check if the registry is empty.
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

/// Global node registry singleton, lazily initialized.
static NODE_REGISTRY: OnceLock<NodeRegistry> = OnceLock::new();

/// Access the global node registry.
pub fn nodes() -> &'static NodeRegistry {
    NODE_REGISTRY.get_or_init(NodeRegistry::new)
}

/// Global registry of active subscriptions.
pub struct SubscriptionRegistry {
    subscriptions: RwLock<HashMap<SubscriptionHandle, SubscriptionState>>,
    next_handle: AtomicUsize,
}

impl SubscriptionRegistry {
    fn new() -> Self {
        Self {
            subscriptions: RwLock::new(HashMap::new()),
            next_handle: AtomicUsize::new(1),
        }
    }

    /// Insert a new subscription state and return its handle.
    pub fn insert(&self, state: SubscriptionState) -> SubscriptionHandle {
        let handle = self.next_handle.fetch_add(1, Ordering::SeqCst);
        let mut subs = self.subscriptions.write();
        subs.insert(handle, state);
        handle
    }

    /// Get mutable access to a subscription state (required for try_recv).
    pub fn get_mut<F, R>(&self, handle: SubscriptionHandle, f: F) -> Option<R>
    where
        F: FnOnce(&mut SubscriptionState) -> R,
    {
        let mut subs = self.subscriptions.write();
        subs.get_mut(&handle).map(f)
    }

    /// Remove and return a subscription state.
    pub fn remove(&self, handle: SubscriptionHandle) -> Option<SubscriptionState> {
        let mut subs = self.subscriptions.write();
        subs.remove(&handle)
    }

    /// Remove all subscriptions for a given node handle.
    pub fn remove_for_node(&self, node_handle: NodeHandle) -> Vec<SubscriptionState> {
        let mut subs = self.subscriptions.write();
        let handles_to_remove: Vec<SubscriptionHandle> = subs
            .iter()
            .filter(|(_, state)| state.node_handle == node_handle)
            .map(|(handle, _)| *handle)
            .collect();

        handles_to_remove
            .into_iter()
            .filter_map(|handle| subs.remove(&handle))
            .collect()
    }
}

/// Global subscription registry singleton.
static SUBSCRIPTION_REGISTRY: OnceLock<SubscriptionRegistry> = OnceLock::new();

/// Access the global subscription registry.
pub fn subscriptions() -> &'static SubscriptionRegistry {
    SUBSCRIPTION_REGISTRY.get_or_init(SubscriptionRegistry::new)
}

/// Convenience wrapper for subscription registry access.
pub struct SubscriptionsAccess;

impl SubscriptionsAccess {
    pub fn insert(&self, state: SubscriptionState) -> SubscriptionHandle {
        subscriptions().insert(state)
    }

    pub fn get_mut<F, R>(&self, handle: SubscriptionHandle, f: F) -> Option<R>
    where
        F: FnOnce(&mut SubscriptionState) -> R,
    {
        subscriptions().get_mut(handle, f)
    }

    pub fn remove(&self, handle: SubscriptionHandle) -> Option<SubscriptionState> {
        subscriptions().remove(handle)
    }

    pub fn remove_for_node(&self, node_handle: NodeHandle) -> Vec<SubscriptionState> {
        subscriptions().remove_for_node(node_handle)
    }
}

/// Global SUBSCRIPTIONS accessor.
pub static SUBSCRIPTIONS: SubscriptionsAccess = SubscriptionsAccess;

/// Convenience wrapper for NODES access (backwards compatibility).
pub struct NodesAccess;

impl NodesAccess {
    pub fn insert(&self, state: NodeState) -> NodeHandle {
        nodes().insert(state)
    }

    pub fn get<F, R>(&self, handle: NodeHandle, f: F) -> Option<R>
    where
        F: FnOnce(&NodeState) -> R,
    {
        nodes().get(handle, f)
    }

    pub fn remove(&self, handle: NodeHandle) -> Option<NodeState> {
        nodes().remove(handle)
    }
}

/// Global NODES accessor for backwards compatibility.
pub static NODES: NodesAccess = NodesAccess;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_registry_handles() {
        // Handles should be non-zero and incrementing
        let registry = nodes();
        assert!(registry.is_empty() || registry.len() > 0);
    }
}
